# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 19:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20160421_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.datetime(2016, 4, 21, 19, 43, 40, 685793, tzinfo=utc)),
        ),
    ]
