# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 19:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20160421_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
